$ANSIBLE_VAULT;1.1;AES256
62346562646532373161366333316631353435323631653636666538323865303763343866646263
3436336335333936383331666330643538363630316262310a353031393537646235666133613063
34376534363062363139313366613032616338343265373837363532313330616266623537623330
6539326230616262360a316134316239316466663662376434613837356461626230313765653563
34346531616165633239653638323662303032303833633065623665643136366366