  - name: Create a system user roboshop
    ansible.builtin.user:
      name: roboshop
      home: /app
      system: true
      shell: /sbin/nologin
      comment: "roboshop system user"

  - name: delete a app directory
    ansible.builtin.file:
      path: /app
      state: absent

  - name: Create a app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: delete zip file
    ansible.builtin.file:
      path: /tmp/{{ ansible_role_name }}.zip
      state: absent

  - name: Download {{ ansible_role_name }} code
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/{{ ansible_role_name }}-v3.zip
      dest: /tmp/{{ ansible_role_name }}.zip

  - name: Unarchive 
    ansible.builtin.unarchive:
      src: /tmp/{{ ansible_role_name }}.zip
      dest: /app
      remote_src: yes