  - name: copy {{ actual_component | default(component) }} service
    ansible.builtin.template:
      src: "{{ actual_component | default(component) }}.service.j2"
      dest: /etc/systemd/system/{{ actual_component | default(component) }}.service
  
  - name: daemon reload
    ansible.builtin.systemd_service:
      daemon_reload: true

